/* Redux action event symbolic names */

const CONNECT_WEB4_CLIENT = 'CONNECT_WEB4_CLIENT';
const CONNECT_WEAVE_CLIENT = 'CONNECT_WEAVE_CLIENT';
const GET_TOKENS = 'GET_TOKENS';
const GET_ACCOUNT_DETAIL = 'GET_ACCOUNT_DETAIL';
const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
const SEND_TRANSACTION = 'SEND_TRANSACTION';
const SEND_SWAP_OFFER = 'SEND_SWAP_OFFER';
const SEND_SWAP_COUNTER = 'SEND_SWAP_COUNTER';
const SEND_SWAP_RELEASE = 'SEND_SWAP_RELEASE';
const GET_SWAP_OFFERS = 'GET_SWAP_OFFERS';
const GET_SENT_SWAP_OFFERS = 'GET_SENT_SWAP_OFFERS';

const MAKE_KEY = 'MAKE_KEY';
const GET_KEY = 'GET_KEY';
const GET_PUBKEY = 'GET_PUBKEY';

module.exports = {
  CONNECT_WEB4_CLIENT,
  CONNECT_WEAVE_CLIENT,
  GET_TOKENS,
  GET_ACCOUNT_DETAIL,
  GET_TRANSACTIONS,
  SEND_TRANSACTION,
  SEND_SWAP_OFFER,
  SEND_SWAP_COUNTER,
  SEND_SWAP_RELEASE,
  GET_SWAP_OFFERS,
  GET_SENT_SWAP_OFFERS,
  MAKE_KEY,
  GET_KEY,
  GET_PUBKEY,
};
